### ISSUE TITLE
The Plugin in slow

### ISSUE THREAD

**Issue by Adigun07** [Jezda1337/nvim-html-css#8]
I use windows and when i type a class it is very slow example
<div class="some-classname"></div>
when i type in the quotation marks neovim takes time to respond
a link to my config is https://github.com/Adigun07/nvim

**Comment by Jezda1337** [comment]
I'm currently working on that issue, the problem is, when every you try to type inside class or id the plugin check for changes inside local files, like html for internal and external changes, fetch style from external styles and parse them. I'm looking for better solution here. And I didn't test it on windows, so I can't talk about that. On Linux and Mac work pretty fast for me.

**Comment by Adigun07** [comment]
yeah i tested it on wsl and it works better
